### ISSUE TITLE
Always getting 'not completed'

### ISSUE THREAD

**Issue by inrakesh** [cloudsight/cloudsight-android-sdk#5]
Getting following in **override fun imageUploaded(response: CloudSightResponse?)** most of the times.

status : **"not completed"**
token : **eYwmFZJ-HzDZ869W1_YJeA**
url : **https://assets.cloudsight.ai/uploads/image_request/image/732/732379/732379723/myfile.jpg**

**Comment by ivied** [comment]
Fixed in 66cc9867ae995b156d506a62a99cf33db878c421
